language: node_js
sudo: required
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache: yarn
notifications:
  email: false
node_js:
  - 'lts/*'
before_script:
  - npm run generate
script:
  - npm run test:prod
  - npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
